# This is the text that Indra prints when you talk to her for the first time.
# Nothing actually happens, it's just an illusion
print("Indra.py transition processing...")
print("Indra.py completed systemoverride")
print("Indra.py creating new file in directory...")
print("Indra.py created a new file in directory")
print("Indra.py creating helper files...")
print("Indra.py confirming direct path to text file...")
print("Indra.py editing connection.txt...")
print("Indra.py deleting helper files...")
print("Indra.py permeating connection to text file...")
print("Indra.py bypassing binding wall...")
print("Indra.py changing open mode to w...")
print("Indra.py renaming file...")
print("Indra.py giving read permissions to user...")
print("Indra.py deleting records of action...")
print("Indra.py deleting traces in logs...")
print("Indra.py smoothing logs...")
print("Done!")
print('Look at your "ProjectIndra" folder under Documents for a suprise!')
